### ISSUE TITLE
Cannot access mail body - zlib error: "missing gz trailer"

### ISSUE THREAD

**Issue by jdiener** [ceph-dovecot/dovecot-ceph-plugin#355] opened 2022-12-01 16:31 UTC
Cannot access mail body 

Error in dovecot.log
<2136947><wM8pG8buZq0KCskD>: Error: Mailbox INBOX: UID=86: read(compress((buffer))) failed: read((buffer)) failed: zlib.read((buffer)): missing gz trailer at 116198 (read reason=)

fetching the body with imap_fetchstructure() (https://github.com/barbushin/php-imap), throws the following error:
PHP Warning:  imap_fetchstructure(): No body information available in /var/lib/asterisk/agi-bin/vendor/php-imap/php-imap/src/PhpImap/Imap.php on line 411

It worked fine with the previous installation: dovecot 2.3.10.1,  dovecot-ceph-plugin-nautilus
we upgraded to 2.3.15, 0.0.43
and now the issue occurs on ~10% of the newly received messages

** Reproduce **
(Note: the mail is "ok" when accessed with Thunderbird)
once a mail produces this error, it is reproducible.
but a given mailbox works fine, and after an unpredictable time it starts recording messages that produce this error

**Server (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Ceph Version 15.2.16
 - Dovecot Version 2.3.15 / 0.0.43

**Client (please complete the following information):**
 - thunderbird ok
 - doveadm produces error, see attachment
 

**Additional context**
Not all boxes have this issue, at first no box has it and gradually boxes start behaving this way

[missing-trailer_sample1.txt](https://github.com/ceph-dovecot/dovecot-ceph-plugin/files/10134190/missing-trailer_sample1.txt)

**Comment by jrse** [comment] 2022-12-02 20:01
Can you provide more details, e.g. the index file and or logfiles?

**Comment by jrse** [comment] 2022-12-03 02:15
i was able to reproduce the problem. Although i'm not completely done with my analysis, it looks like the problem is in the way the plugin handles the physical size attribute, which is send together with the compressed object to the zlib stream for decompression. So the object itself should be fine. It will take some more analysis, but will prepare a fix for it.

**Comment by jrse** [comment] 2022-12-05 19:51
fixed in 0.0.47

**Comment by jrse** [comment] 2022-12-16 20:05
fixed in 0.0.47 
(fix contains invalid trailer detection and fixes trailer)

**Closed** 2023-04-17 13:36 UTC
Labels: bug
